"""reg-guardcheck — the in-CI guard-file notification.

The instructor-side check (``lectern.triage_guardfile``) reads git history from
outside the student's control and is the authoritative record. This is the other
half: a check that runs inside the lab's own autograde workflow so the **student
is told**, in the run they already look at, that a file they were not asked to
edit has changed.

==It notifies. It does not grade.== No points, no pass/fail, and it always exits
0 unless ``--strict`` is passed, because a student's CI failing over a file that
does not affect their program is a bad way to open a conversation. A repo can
edit its own workflow, so nothing here is evidence; the sweep is.

Stdlib only, on purpose: a lab template can vendor this one file as
``grading/guardcheck.py`` and run it with bare ``python3``.

Instructor, once per template::

    reg-guardcheck stamp --repo <template> AGENTS.md   # writes grading/guard.sha256

In the lab's autograde workflow, after the grader has written its result::

    - run: python3 grading/guardcheck.py check --result grading/result.json
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys
from pathlib import Path

MANIFEST = "grading/guard.sha256"

STATUS_INTACT = "intact"
STATUS_MODIFIED = "modified"
STATUS_MISSING = "missing"

#: What the student reads. Plain, unaccusing, and it says what happens next.
MESSAGES = {
    STATUS_MODIFIED: (
        "{path} has been modified. It is course material, not part of your "
        "submission, and changing it does not change the assignment or your "
        "grade. Your instructor sees the edit in the commit history. If this "
        "was not deliberate, restore it with: git checkout <first-commit> -- {path}"
    ),
    STATUS_MISSING: (
        "{path} is missing. It is course material, not part of your submission, "
        "and deleting it does not change the assignment or your grade. Your "
        "instructor sees the deletion in the commit history. Restore it with: "
        "git checkout <first-commit> -- {path}"
    ),
}


def sha256_file(path: Path) -> str | None:
    """Hex digest of *path*, or None when it is not there."""
    try:
        return hashlib.sha256(path.read_bytes()).hexdigest()
    except OSError:
        return None


def write_manifest(repo: Path, paths: list[str], out: Path) -> list[tuple[str, str]]:
    """Stamp the expected digests. Format is ``sha256sum``-compatible on purpose,
    so ``sha256sum -c`` verifies it with no tooling at all."""
    rows = []
    for rel in paths:
        digest = sha256_file(repo / rel)
        if digest is None:
            raise FileNotFoundError(f"{rel} not found in {repo}")
        rows.append((digest, rel))
    out.parent.mkdir(parents=True, exist_ok=True)
    body = "".join(f"{d}  {p}\n" for d, p in rows)
    out.write_text(
        "# Guard files: course material, not part of the submission.\n"
        "# Generated by reg-guardcheck stamp. Verify with: sha256sum -c "
        + out.name + "\n" + body
    )
    return rows


def read_manifest(path: Path) -> list[tuple[str, str]]:
    """Parse a ``sha256sum``-format manifest into (digest, relative path) rows."""
    rows = []
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split(None, 1)
        if len(parts) != 2:
            continue
        rows.append((parts[0].lower(), parts[1].strip().lstrip("*")))
    return rows


def check(repo: Path, rows: list[tuple[str, str]]) -> list[dict]:
    """Compare each expected digest against the working tree."""
    results = []
    for expected, rel in rows:
        actual = sha256_file(repo / rel)
        if actual is None:
            status = STATUS_MISSING
        elif actual == expected:
            status = STATUS_INTACT
        else:
            status = STATUS_MODIFIED
        results.append({"path": rel, "status": status,
                        "expected": expected, "actual": actual})
    return results


def _annotate(result: dict) -> None:
    """Emit a GitHub Actions annotation so the notice lands on the run itself."""
    if not os.environ.get("GITHUB_ACTIONS"):
        return
    message = MESSAGES[result["status"]].format(path=result["path"])
    # Annotations are single-line; the workflow-command escape is %0A for a newline.
    print(f"::notice title=Course file changed::{message}")


def render(results: list[dict]) -> str:
    """The human block printed in the run log."""
    changed = [r for r in results if r["status"] != STATUS_INTACT]
    if not changed:
        n = len(results)
        return f"Guard files: {n} checked, all unchanged."
    lines = ["", "=" * 68, "Course files changed", "=" * 68, ""]
    for r in changed:
        lines += [MESSAGES[r["status"]].format(path=r["path"]), ""]
    lines += ["This check does not affect your grade.", "=" * 68, ""]
    return "\n".join(lines)


def merge_notices(result_path: Path, results: list[dict]) -> bool:
    """Record the notices in an existing ``result.json``. Never creates one:
    a result file conjured out of nothing reads downstream as a zero-point run."""
    if not result_path.exists():
        return False
    try:
        data = json.loads(result_path.read_text())
    except (OSError, ValueError):
        return False
    if not isinstance(data, dict):
        return False
    data["notices"] = [
        {"key": "guard_file", "level": "notice", "path": r["path"],
         "status": r["status"],
         "message": MESSAGES[r["status"]].format(path=r["path"])}
        for r in results if r["status"] != STATUS_INTACT
    ]
    result_path.write_text(json.dumps(data, indent=2, sort_keys=True))
    return True


def _cmd_stamp(args) -> int:
    repo = Path(args.repo)
    out = Path(args.out) if args.out else repo / MANIFEST
    rows = write_manifest(repo, args.paths, out)
    print(f"wrote {out}")
    for digest, rel in rows:
        print(f"  {digest[:16]}…  {rel}")
    return 0


def _cmd_check(args) -> int:
    repo = Path(args.repo)
    manifest = Path(args.manifest) if args.manifest else repo / MANIFEST
    if not manifest.exists():
        # No manifest is not a student problem: the lab was never stamped.
        print(f"guardcheck: no manifest at {manifest}; nothing to check.")
        return 0

    results = check(repo, read_manifest(manifest))
    print(render(results))
    for r in results:
        if r["status"] != STATUS_INTACT:
            _annotate(r)

    if args.result:
        merge_notices(Path(args.result), results)
    if args.json:
        Path(args.json).write_text(json.dumps(results, indent=2, sort_keys=True))

    changed = [r for r in results if r["status"] != STATUS_INTACT]
    # Exit 0 by default: this is a notification, not a grade.
    return 1 if (changed and args.strict) else 0


def main(argv=None) -> int:
    p = argparse.ArgumentParser(
        prog="reg-guardcheck",
        description="Notify (never grade) when course files in a student repo change.")
    sub = p.add_subparsers(dest="cmd", required=True)

    ps = sub.add_parser("stamp", help="record the expected digests (instructor, once)")
    ps.add_argument("paths", nargs="+", help="repo-relative guard files, e.g. AGENTS.md")
    ps.add_argument("--repo", default=".", help="template repo root (default: .)")
    ps.add_argument("--out", default=None, help=f"manifest path (default: <repo>/{MANIFEST})")
    ps.set_defaults(func=_cmd_stamp)

    pc = sub.add_parser("check", help="compare the working tree against the manifest")
    pc.add_argument("--repo", default=".", help="student repo root (default: .)")
    pc.add_argument("--manifest", default=None, help=f"default: <repo>/{MANIFEST}")
    pc.add_argument("--result", default=None,
                    help="existing result.json to record the notices in (optional)")
    pc.add_argument("--json", default=None, help="write the raw findings here (optional)")
    pc.add_argument("--strict", action="store_true",
                    help="exit non-zero on a change (off by default: this notifies, "
                         "it does not grade)")
    pc.set_defaults(func=_cmd_check)

    args = p.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
